### ISSUE TITLE
local references in atSNP/tests/test.R

### ISSUE THREAD

**Issue by paul-shannon** [chandlerzuo/atSNP#13]
Delighted to discover atSNP, to use (possibly) as an alternative to the FIMO web service.  As I install, test, and learn to use your package, I ran into a few difficulties.  I hope you do not mind if I mention them here:

You may want to modify your test.R to avoid ````source```` calls, and to remove the local references:

    /p/keles/ENCODE-CHARGE/volume2/SNP/hg19_allinfo.bed
     ~/atsnp_git/*

The recommended R package practice, I believe, is to export R functions from the NAMESPACE, and to load data from the installed package via

````system.file(package='atSNP', "data", "gwas_snp1.txt")````

If your package is a powerful as it, on first look, appears to be, you may wish to submit to Biocondcutor, and get their assistance on matters like these, and to spread the word on its usefulness.

 - Paul

**Comment by chandlerzuo** [comment]
Thank you! This is long over-due, but I think @sunyoungshin finished it in https://github.com/chandlerzuo/atSNP/commit/db78813d276b097c4e119eaa09b6f116512c5f1a#diff-eecfc841bc920999bfcbf576316f8cea.
