### ISSUE TITLE
error in ComputeMotifScore: error in startParallel

### ISSUE THREAD

**Issue by kinsigne** [chandlerzuo/atSNP#14]
When running the` computeMotifScore()` function, I receive this error: 

`Error in startParallel(ncores) : could not find function "Return"`

Looking at the `R/utility.R` file in the `startParallel` function, at the end of the function is the return statement: `Return("cl")`.

Is this a typo and Return shouldn't be capitalized? Or am I missing some other package that has the correct `Return` function?

Thanks!

**Comment by kinsigne** [comment]
Also, not sure if the string "cl" should be returned or the actual cluster object itself `cl`.

**Comment by chandlerzuo** [comment]
Thank you! This is long overdue, but I think @sunyoungshin has fixed this.
