### ISSUE TITLE
p-value stability

### ISSUE THREAD

**Issue by kwcurrin** [chandlerzuo/atSNP#21]
Hello,

Sometimes the p-values reported by atSNP can vary quite a bit. I noticed this when I reran atSNP a second time with a motif library that was a superset of the motif library used for the first atSNP run. Therefore, I tried running two motifs through atSNP 10 separate times. When I did this, I got identical results each time, which were:
M6510_1.02, rs11644920:
pval_ref: 0.0091
pval_snp: 0.023
pval_rank: 0.13

M3031_1.02, rs3784924:
pval_ref: 0.0029
pval_snp: 0.018
pval_rank: 0.042

However, when I ran motif M3031_1.02 through atSNP on its own, I got different results:
M3031_1.02, rs3784924:
pval_ref: 1.1e-07
pval_snp: 0.022
pval_rank: 0

The above results were stable across 10 trials. However, the p-values for M6510_1.02 did not change when I ran it through atSNP on its own. 

Is it possible that other motifs in a motif library could somehow impact the p-value calculations of another motif? This doesn't seem likely because the code for ComputePValues() seems to treat each motif separately. However, I can't figure out why running atSNP on M3031_1.02 by itself produces different results than with M3031_1.02 and M6510_1.02.

I replicated the above results with both ncores=1 and ncores=4. I also tried reloading atSNP between each atSNP run, but that didn't change anything.

Do you have any ideas as to what might be going on?

Thanks!

Kevin

**Comment by kwcurrin** [comment]
Some additional info to help troubleshoot:
R version: 3.3.1
atSNP version: 1.0

The log likelihoods for ref and snp do not change for M3031_1.02, but the p-values do. The p-values and log likelihoods are:
Ran by itself:
M3031_1.02, rs3784924:
pval_ref: 1.1e-07
pval_snp: 0.022
pval_rank: 0
log_lik_ref: -11.4524871252634
log_lik_snp: -12.6564562629257

Ran with two other motifs:
M3031_1.02, rs3784924:
pval_ref: 0.0029
pval_snp: 0.018
pval_rank: 0.042
log_lik_ref: -11.4524871252634
log_lik_snp: -12.6564562629257

I get a third set of p-values when running M3031_1.02 alongside 515 other motifs (which was where I first discovered the issue):
pval_ref: 1.8e-07
pval_snp: 0.0015
pval_rank: 3.2e-05
log_lik_ref: -11.45249
log_lik_snp: -12.65646

**Comment by chandlerzuo** [comment]
Hi Kevin,

P-values are independently calculate for each motif. They are computed by Monte-Carlo sampling, so variance is expected, and variance is larger for SNPs with small p-values. I think that is why you observe variance in one SNP but not the other.

To reduce variance:

1. Increasing Monte-Carlo sample size. We don't expose this option in ComputePValues, but there is an indirect way -- include the number of SNPs in your analysis. If you do so, the SNPs with the least p-values will have large Monte-Carlo sample size, which in return gives more accurate computation.
2. Run multiple times and take the average. Each run gives unbiased estimation for the "true" p-value, so taking the average of multiple runs leads to higher accuracy.

Hope this helps!

**Comment by kwcurrin** [comment]
Hi Chandler,

Thanks for your suggestions. However, I don't think that the monte-carlo simulations are the issue for two reasons:
1. When I run the same two motifs through 10 times, I get identical results. I have actually ran it more like 30 or 40 times because I have repeated the script that runs atSNP 10 times and still got identical results. The only change is when I change the number of motifs or the number of SNPs.
2. The p-value for M3031_1.02 for the given SNP is not very small (0.0029) for most of the runs. It only decreases to 1.1e-7 for certain runs. I have ran this SNP-motif combination through fimo and the smallest p-value is 3e-4, which is also not very small.


I think this could result from how the afinity scores are separated into bins when calculating parameters for the sampling distributions. Depending on how many SNPs/motifs are included, a given motif-SNP pair could be groupped into different bins, resulting in different parameters for the sampling distribution used for p-value calculation. This would explain why I get identical results when running the same number of SNPs/motifs through multiple times, but different results when adding or removing motifs from the analysis. 

What do you think?

Thanks!

Kevin

**Comment by kwcurrin** [comment]
Could you clarify if this is correct? This is just my best guess.
