### ISSUE TITLE
Correct setting for testing.mc in the ComputePValues function

### ISSUE THREAD

**Issue by jrm3215** [chandlerzuo/atSNP#22]
Hello,

I really like atSNP and appreciate the time and effort spent on creating it!

Can you confirm that the correct setting for real-world use of the ComputePValues function is 'testing.mc=FALSE'?

If so, I think this should be noted in the vignette.

**Comment by chandlerzuo** [comment]
Thanks for noting this. You are right. I have updated this in the vignette.

**Comment by chandlerzuo** [comment]
Closed by https://github.com/chandlerzuo/atSNP/commit/268add2998bd74d7353ef283fc29d24c6b012904
